sudo: required
services:
  - docker

before_install:
  - docker build -t kiily/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kiily/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend-docker-nginx-example"
  env: "FrontendDockerNginxExample-env"
  bucket_name: "elasticbeanstalk-us-east-2-008501372495"
  bucket_path: "frontend-docker-nginx-example"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
